#!/bin/sh

if [ $# -ne 0 ]
then
	echo "Usage: $0" >&2
	exit 1
fi

old_flags=$(
mpc status \
	| tail -1 \
	| sed 's/: */:/g' \
	| tr ' ' '\n' \
	| sed '/^$/d; /n\/a/d'
)

restore_mpc_state(){
	for flag in $old_flags
	do
		name=${flag%:*}
		value=${flag#*:}
		mpc $name $value >/dev/null
	done
}

trap restore_mpc_state EXIT INT

{
	mpc single on
	mpc repeat off
} > /dev/null
mpc-waitforsong
