#!/bin/sh

#	Usage: $0 [grep args]

curtrack(){
	mpc | head -1
}

playing(){
	curtrack | grep "$@" > /dev/null
	return $?
}

sleep_on_mpd(){
	mpc idle player >/dev/null
}

if test $# -eq 0
then
	now=`curtrack`
	while playing -F "$now"
	do sleep_on_mpd
	done
else
	while ! playing "$@"
	do sleep_on_mpd
	done
fi
